import { InventoryItem } from '../types';

export const INITIAL_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: 'inv-item-001',
    sku: 'WLD-TIP-1.2-M6',
    name: 'MIG Contact Tip 1.2mm CuCrZr Heavy-Duty M6x28',
    category: 'MIG Consumables & Spares',
    hsnCode: '85159000',
    unit: 'PCS',
    unitPriceINR: 48,
    unitPriceUSD: 0.60,
    costPriceINR: 28,
    gstRatePct: 18,
    currentStock: 1250,
    minStockAlert: 200,
    isPublic: false,
    warehouseLocation: 'Jamnagar Plant Godown A - Rack B12',
    status: 'In Stock',
    supplierName: 'Earth Metal Industries In-House CNC Brass Cell',
    description: 'High-thermal-conductivity copper contact tip engineered for continuous robotic & manual MIG welding.',
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'inv-item-002',
    sku: 'WLD-NOZ-501D',
    name: 'Conical Gas Nozzle MB-501D Water-Cooled (Cu)',
    category: 'MIG Consumables & Spares',
    hsnCode: '85159000',
    unit: 'PCS',
    unitPriceINR: 245,
    unitPriceUSD: 2.95,
    costPriceINR: 140,
    gstRatePct: 18,
    currentStock: 18,
    minStockAlert: 25,
    isPublic: false,
    warehouseLocation: 'Jamnagar Plant Godown A - Bin C-04',
    status: 'Low Stock',
    supplierName: 'Earth Metal Industries Pressings Bay',
    description: 'Heavy gauge chrome-plated copper nozzle for shielding gas distribution in 500A MIG torches.',
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'inv-item-003',
    sku: 'WLD-VALV-24V-52',
    name: '5/2 Way Solenoid Valve 24V DC 1/4" BSP Automation',
    category: 'Pneumatic Automation Valves',
    hsnCode: '84818030',
    unit: 'PCS',
    unitPriceINR: 1480,
    unitPriceUSD: 17.50,
    costPriceINR: 920,
    gstRatePct: 18,
    currentStock: 0,
    minStockAlert: 10,
    isPublic: false,
    warehouseLocation: 'Automation Assembly Section - Rack E2',
    status: 'Out of Stock',
    supplierName: 'Earth Pneumatics Sub-Assembly',
    description: 'Pilot-operated direction control valve with manual override for industrial machine jigs.',
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'inv-item-004',
    sku: 'WLD-FITT-PC08-02',
    name: 'Brass Male Stud Push-In Fitting 8mm OD x 1/4" BSPT',
    category: 'Brass Pneumatic Fittings',
    hsnCode: '74122019',
    unit: 'PCS',
    unitPriceINR: 64,
    unitPriceUSD: 0.78,
    costPriceINR: 36,
    gstRatePct: 18,
    currentStock: 3400,
    minStockAlert: 500,
    isPublic: true,
    warehouseLocation: 'Jamnagar Brass Godown 1 - Aisle 3',
    status: 'In Stock',
    supplierName: 'Earth Metal Industries Jamnagar Foundry & CNC',
    description: 'Nickel-plated brass push-in fitting with NBR O-ring sealing for airline pipelines.',
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'inv-item-005',
    sku: 'WLD-ROD-CW617N-25',
    name: 'Forging Grade Brass Hex Rod CW617N 25mm A/F (3 Mtr)',
    category: 'Raw Materials & Extrusions',
    hsnCode: '74072110',
    unit: 'KG',
    unitPriceINR: 685,
    unitPriceUSD: 8.20,
    costPriceINR: 590,
    gstRatePct: 18,
    currentStock: 8,
    minStockAlert: 15,
    isPublic: false,
    warehouseLocation: 'Raw Material Yard - Bay 1 Raw Rack 4',
    status: 'Low Stock',
    supplierName: 'Earth Extrusions Plant Jamnagar',
    description: 'High-machinability leaded brass rod stock for high-pressure valve bodies.',
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'inv-item-006',
    sku: 'WLD-WIRE-ER70S6-15KG',
    name: 'Copper-Coated MIG Solid Wire ER70S-6 1.2mm (15kg Spool)',
    category: 'Welding Wire & Spools',
    hsnCode: '72292000',
    unit: 'BOX',
    unitPriceINR: 1950,
    unitPriceUSD: 23.50,
    costPriceINR: 1450,
    gstRatePct: 18,
    currentStock: 142,
    minStockAlert: 30,
    isPublic: false,
    warehouseLocation: 'Godown B - Finished Spool Pallet 7',
    status: 'In Stock',
    supplierName: 'Weldor Wire Drawing Division',
    description: 'Precision layer-wound solid wire with deoxidizers for smooth arc & minimal spatter.',
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'inv-item-007',
    sku: 'WLD-DIF-501D-CER',
    name: 'DMC Gas Diffuser White MB-501D High-Temp',
    category: 'MIG Consumables & Spares',
    hsnCode: '85159000',
    unit: 'PCS',
    unitPriceINR: 38,
    unitPriceUSD: 0.45,
    costPriceINR: 19,
    gstRatePct: 18,
    currentStock: 0,
    minStockAlert: 50,
    isPublic: false,
    warehouseLocation: 'Consumable Bin D-11',
    status: 'Out of Stock',
    supplierName: 'Earth Plastic & Ceramics Molding Div',
    description: 'Heat resistant thermoset insulator diffuser for steady laminar shielding gas flow.',
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'inv-item-008',
    sku: 'WLD-TRCH-MIG500-3M',
    name: 'Weldor Pro-500 Heavy-Duty Water-Cooled MIG Torch (3 Mtr)',
    category: 'Welding Torches & Assemblies',
    hsnCode: '85153990',
    unit: 'SET',
    unitPriceINR: 9800,
    unitPriceUSD: 118.00,
    costPriceINR: 6400,
    gstRatePct: 18,
    currentStock: 26,
    minStockAlert: 8,
    isPublic: true,
    warehouseLocation: 'Assembly Line Finished Store - Rack F1',
    status: 'In Stock',
    supplierName: 'Weldor Torch Assembly Unit',
    description: 'Complete torch assembly with Euro connection, ball joint, ergonomic handle.',
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'inv-item-009',
    sku: 'WLD-TUNG-WT20-2.4',
    name: 'Thoriated Red Tungsten Electrode WT20 2.4mm x 175mm',
    category: 'TIG Consumables',
    hsnCode: '81019990',
    unit: 'PACK',
    unitPriceINR: 850,
    unitPriceUSD: 10.20,
    costPriceINR: 520,
    gstRatePct: 18,
    currentStock: 95,
    minStockAlert: 20,
    isPublic: false,
    warehouseLocation: 'Precision Cabinet 2 - Shelf A',
    status: 'In Stock',
    supplierName: 'Refractory Metals Partner',
    description: 'Pack of 10 electrodes for high current DC TIG welding on carbon & stainless steels.',
    lastUpdated: new Date().toISOString()
  },
  {
    id: 'inv-item-010',
    sku: 'WLD-CYL-ISO6431-63X100',
    name: 'ISO 6431 Tie-Rod Pneumatic Cylinder 63mm Bore x 100mm Stroke',
    category: 'Pneumatic Cylinders',
    hsnCode: '84123100',
    unit: 'PCS',
    unitPriceINR: 3450,
    unitPriceUSD: 41.50,
    costPriceINR: 2100,
    gstRatePct: 18,
    currentStock: 5,
    minStockAlert: 10,
    isPublic: true,
    warehouseLocation: 'Cylinder Godown - Bay 4',
    status: 'Low Stock',
    supplierName: 'Weldor Pneumatics Division',
    description: 'Hard-anodized aluminum barrel with magnetic piston & adjustable air cushioning.',
    lastUpdated: new Date().toISOString()
  }
];
